name: cifar10
root: ./data/cifar10
num_classes: 10
img_size: 32
normalize:
  mean: [0.4914, 0.4822, 0.4465]
  std:  [0.2023, 0.1994, 0.2010]
augment:
  color_jitter: [0.4, 0.4, 0.4, 0.4]
  random_gray: 0.2
  hflip: false
batch_size: 128
num_workers: 4
pin_memory: true
download: true
