name: stl10
root: ./data/stl10
num_classes: 10
img_size: 96
normalize:
  mean: [0.4467, 0.4398, 0.4066]
  std:  [0.2603, 0.2566, 0.2713]
augment:
  color_jitter: [0.4, 0.4, 0.4, 0.4]
  random_gray: 0.2
  hflip: true
batch_size: 128
num_workers: 4
pin_memory: true
download: true
