name: tinyimagenet
root: ./data/tiny-imagenet-200
num_classes: 200
img_size: 64
normalize:
  mean: [0.485, 0.456, 0.406]
  std:  [0.229, 0.224, 0.225]
augment:
  color_jitter: [0.4,0.4,0.4,0.4]
  random_gray: 0.2
  hflip: true
batch_size: 256
num_workers: 4
pin_memory: true
download: false
