max_epochs: 200
rounds: 5
optimizer:
  name: sgd
  lr: 0.03
  momentum: 0.9
  weight_decay: 5e-4
  nesterov: true
lr_schedule:
  policy: step
  step: 40
  gamma: 0.1
  offset: 80
model:
  backbone: resnet18
  low_dim: 128
  projector:
    dims: [512, 512, 128]
  autok_head:
    enabled: true
    method: "consensus"     # "silhouette"|"xmeans"|"eigengap"|"dpmeans"|"consensus"
    sweep:
      k_min: 2
      k_max: 100
      step: 2
    update_freq: 1          # epochs between K updates
    min_delta: 0.01         # stability margin
    warmup_epochs: 10
loss:
  name: and
  npc_temperature: 0.1
  npc_momentum: 0.5
  lambda_cluster: 1.0       # weight for clustering regularizer
display_freq: 100
